services:
  servidor:
    build: ./server
    networks:
      rede_tarefas:
        ipv4_address: 172.25.0.10

  cliente1:
    build: ./client
    environment:
      - SERVIDOR_ENDERECO=172.25.0.10:50051
    networks:
      rede_tarefas:
        ipv4_address: 172.25.0.11
    stdin_open: true
    tty: true
    depends_on:
      - servidor

  cliente2:
    build: ./client
    environment:
      - SERVIDOR_ENDERECO=172.25.0.10:50051
    networks:
      rede_tarefas:
        ipv4_address: 172.25.0.12
    stdin_open: true
    tty: true
    depends_on:
      - servidor

networks:
  rede_tarefas:
    ipam:
      config:
        - subnet: 172.25.0.0/24