# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tarefas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtarefas.proto\x12\x07tarefas\"r\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x05 \x01(\t\x12\x14\n\x0cresponsaveis\x18\x06 \x03(\t\"r\n\x12\x43riarTarefaRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x04 \x01(\t\x12\x14\n\x0cresponsaveis\x18\x05 \x03(\t\"\x07\n\x05Vazio\"0\n\x0cListaTarefas\x12 \n\x07tarefas\x18\x01 \x03(\x0b\x32\x0f.tarefas.Tarefa\"\"\n\x14\x44\x65letarTarefaRequest\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x15\x44\x65letarTarefaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\x89\x02\n\rTarefaService\x12;\n\x0b\x43riarTarefa\x12\x1b.tarefas.CriarTarefaRequest\x1a\x0f.tarefas.Tarefa\x12\x36\n\rListarTarefas\x12\x0e.tarefas.Vazio\x1a\x15.tarefas.ListaTarefas\x12\x33\n\x0f\x41tualizarTarefa\x12\x0f.tarefas.Tarefa\x1a\x0f.tarefas.Tarefa\x12N\n\rDeletarTarefa\x12\x1d.tarefas.DeletarTarefaRequest\x1a\x1e.tarefas.DeletarTarefaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAREFA']._serialized_start=26
  _globals['_TAREFA']._serialized_end=140
  _globals['_CRIARTAREFAREQUEST']._serialized_start=142
  _globals['_CRIARTAREFAREQUEST']._serialized_end=256
  _globals['_VAZIO']._serialized_start=258
  _globals['_VAZIO']._serialized_end=265
  _globals['_LISTATAREFAS']._serialized_start=267
  _globals['_LISTATAREFAS']._serialized_end=315
  _globals['_DELETARTAREFAREQUEST']._serialized_start=317
  _globals['_DELETARTAREFAREQUEST']._serialized_end=351
  _globals['_DELETARTAREFARESPONSE']._serialized_start=353
  _globals['_DELETARTAREFARESPONSE']._serialized_end=411
  _globals['_TAREFASERVICE']._serialized_start=414
  _globals['_TAREFASERVICE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
